name: seqnado
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - snakemake>=9.12.0,<=9.14.5
  - python>=3.10
  - pip
  - pip:
    - tracknado
    - wget
    - snakemake-executor-plugin-slurm<=2.0.3