executor: aws-batch
jobs: 100

use-conda: false
software-deployment-method: apptainer
use-apptainer: true

show-failed-logs: true
printshellcmds: true
retries: 3

default-resources:
    runtime: "1h"
    mem: "3G"
